language: python
python:
    - "2.7"
env:
    - DJANGO_VERSION=1.4
    - DJANGO_VERSION=1.5
install:
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
    # Install ChunkyCMS itself
    - pip install -e .
script: python setup.py test
